site_name: AARC

nav:
    - Home: 'index.md'
    - 'Notes':
        - 'Frameworks, Libraries, and SDKS':
          - 'Revit API':
            - 'Unstructured Notes': 'notes/frameworks_sdks/revit_api/revit.md'
          - 'RhinoCommon':
            - 'Unstructured Notes': 'notes/frameworks_sdks/rhinocommon/rhino.md'
        - 'Tooling':
          - 
    - 'Projects and CV':
        - 'Projects': 'projects_cv/projects.md'
        - 'CV': 'projects_cv/cv.md'
    - About:
        - 'About': 'about/about.md'
        - 'License': 'about/license.md'
        - 'Release Notes': 'about/changelog.md'


theme:
  name: material
